export const mapNameKoMap: Record<string, Record<string, string>> = {
  "bounty": {
    "below zero": "영하",
    "block party": "블로킹 파티",
    "bouncy bowl": "통통볼",
    "brace for impact": "충격 대비",
    "cool box": "쿨박스",
    "don't turn around": "돌아보지마",
    "dry season": "햇빛은 쨍쨍",
    "floater": "플로터",
    "hideout": "은신처",
    "jungle ball": "정글 볼",
    "layer cake": "레이어 케이크",
    "no excuses": "변명 금지",
    "pancake": "팬케이크",
    "power alley": "파워 앨리",
    "shooting star": "별내림 계곡",
    "side by side": "나란히 나란히",
    "slippery slap": "미끌미끌 슬랩",
    "starr garden": "스타정원",
    "starrburst": "스타 버스트",
    "strong side": "스트롱 사이드",
    "super center": "슈퍼센터",
    "tiger leap": "타이거 점프",
  },
  "brawlarena(3vs3)": {
    "7개": "4개",
    "보물 사냥": "브롤 하키 5vs5",
  },
  "brawlball": {
    "arena of glory": "영광의 아레나",
    "backyard bowl": "뒷마당 월드컵",
    "baech ball": "비치볼",
    "center stage": "센터 스테이지",
    "coin flip": "코인 던지기",
    "flaring phoenix": "타오르는 불사조",
    "flute chutes": "좁고 긴 통로",
    "grab the moment": "순간의 포착",
    "grass knot": "풀 매듭",
    "kaiju lake": "괴수 호수",
    "knockout grounds": "녹아웃 그라운드",
    "match 1153581321": "매치 1123581321",
    "mirage arena": "신기루 아레나",
    "monkey maze": "원숭이 미로",
    "no surrender": "항복 없는 결투의 장",
    "pinball dreams": "핀볼 드림",
    "pinhole punt": "핀홀 필드",
    "priceless cactus": "귀중한 선인장",
    "rooftop runners": "옥상 위에 질주",
    "search and destroy": "수색 및 파괴",
    "shrouding serpent": "뒤덮는 뱀",
    "sidetrack": "샛길",
    "sneaky fields": "스키니 필드",
    "spiraling out": "스파이럴 아웃",
    "sunny soccer": "화창한 날",
    "super beach": "슈퍼 해변",
    "the great mighty lou": "매우 강력한 루",
    "the smackdome": "스맥돔",
    "triple dribble": "트리플 드리블",
    "warriors way": "전사의 길",
  },
  "duoshowdown": {
    "acid lakes": "산성 호수",
    "ancient treasure": "고대의 보물",
    "big battle basin": "대형 전투 분지",
    "brawl starrgate": "브롤 스타게이트",
    "can you dig it": "발굴 준비",
    "cavern churn": "우당탕 진흙탕",
    "core of orbit": "궤도의 핵심",
    "crystal eye castle": "수정 눈의 성",
    "double trouble": "더블 트러블",
    "excellent excavations": "위대한 발굴",
    "feast or famine": "모 아님 도",
    "flying fantasies": "플라잉 판타지",
    "frosty tracks": "서리 내린 트랙",
    "gated community": "출입 통제 커뮤니티",
    "hee hee": "히히",
    "hidden in plain sight": "등하불명",
    "icy ice park": "아이스 파크",
    "island of finality": "최후의 섬",
    "kroket": "크로켓",
    "lilypond grove": "우거진 연못",
    "lotus": "로투스",
    "makeshift scaffolding": "임시 발",
    "middle management": "중간 관리자",
    "mirages of madness": "광기의 신기루",
    "mystical thirty three": "신비로운 33",
    "rockwall brawl": "바위 장벽 전투",
    "safety center": "안전 센터",
    "seeker": "시커",
    "skull creek": "해골천",
    "slippery road": "미끌미끌 도로",
    "treasure marks the spot": "보물 표식",
    "truth": "진실",
    "twisting vines": "비틀린 덩쿨",
    "waveform": "파동",
  },
  "gemgrab": {
    "a ballad about minced cutlets": "커틀릿 발라드",
    "acid lakes": "산성 호수",
    "afterparty": "뒤풀이 파티",
    "atlas": "아틀라스",
    "bells rock": "벨스 락",
    "call of the water": "물의 부름",
    "cavern churn": "우당탕 진흙탕",
    "chivalry": "기사도",
    "core of orbit": "궤도의 핵심",
    "crystal arcade": "수정 오락실",
    "crystal eye castle": "수정 눈의 성",
    "deathcap trap": "독버섯 함정",
    "deep end": "딥 엔드",
    "double decker": "더블 데커",
    "double swoosh": "이중 곡선",
    "double trouble": "더블 트러블",
    "extreme nonchalance": "극도의 무관심",
    "feast or famine": "모 아님 도",
    "flaring phoenix": "타오르는 불사조",
    "flowing springs": "흐르는 샘",
    "flying fantasies": "플라잉 판타지",
    "four levels": "네 개의 레벨",
    "gated community": "출입 통제 커뮤니티",
    "gem fort": "보석요새",
    "goldarm gulch": "골드암 협곡",
    "h for...": "핫 뜨거워",
    "hard rock mine": "암석 광산",
    "healthy middle ground": "적당한 중간지점",
    "kroket": "크로켓",
    "lilygear lake": "릴리기어 호수",
    "lilypond grove": "우거진 연못",
    "local restaurants": "로컬 맛집",
    "lotus": "로투스",
    "makeshift scaffolding": "임시 발",
    "mystical thirty three": "신비로운 33",
    "new horizons": "새로운 지평선",
    "new perspective": "새로운 시각",
    "on a roll": "승승장구",
    "open space": "열린 공간",
    "out in the open": "오픈 필드",
    "party for you": "날 위한 파티",
    "railroad robbery": "철로 대도",
    "rockwall brawl": "바위 장벽 전투",
    "rustic arcade": "오래된 오락실",
    "safety center": "안전 센터",
    "seeker": "시커",
    "skull creek": "해골천",
    "storage sector": "저장 구역",
    "streets with no name": "이름 없는 거리",
    "tango": "탱고",
    "think ahead": "미리 준비",
    "truth": "진실",
    "twisting vines": "비틀린 덩쿨",
    "undermine": "흔들 광산",
    "waveform": "파동",
    "whisper vale": "속삭이는 계곡",
  },
  "heist": {
    "afterpiece arena": "에필로그 아레나",
    "all things wicked": "모든 약한 것",
    "alley oop": "앨리웁",
    "ball hog": "볼 호그",
    "bridge too far": "머나먼 다리",
    "broller room": "보일러실",
    "corner cave": "구석진 동굴",
    "foursquare fortress": "네모 요새",
    "gg 2.0": "GG 2.0",
    "hoop boot hill": "언덕을 넘어",
    "hot potato": "뜨거운 감자",
    "kaboom canyon": "우당탕 협곡",
    "kooky gates": "어리둥절 게이트",
    "paperback pond": "종이 연못",
    "photic doom": "빛의 돔",
    "pit stop": "피트 스톱",
    "plain text": "서식 없음",
    "pocket pass": "포켓 패스",
    "reversal": "속공",
    "safe zone": "안전지대",
    "slam dunk": "슬랭 덩크",
    "subway turfers": "서브웨이 터퍼",
    "triple-double": "트리플 더블",
    "turnover": "역전",
    "zip zap zoom": "집 잽 줌",
  },
  "hotzone": {
    "abracadabra": "아브라카다브라",
    "back shuffle": "백 셔플",
    "brawlerverse": "브롤러버스",
    "crescendo": "크레센도",
    "dodge or die": "닷지 오어 다이",
    "dueling beetles": "곤충 싸움",
    "fishing bed": "황금어장",
    "hug or hurl": "안거나 던지거나",
    "in the liminal": "경계속으로",
    "journey of a thousand steps": "수천 걸음의 여정",
    "just another race to anuwhere": "또 다른 경주",
    "moonbark meadow": "달빛 초원",
    "open business": "신장 개업",
    "open zone": "오픈",
    "parallel plays": "평행선",
    "playmaker": "플레이메이커",
    "rebound ring": "리바운드 링",
    "ring of fire": "불의 고리",
    "serpentshrine island": "세르펜슈린 섬",
    "side hustle": "사이드 허슬",
    "squish court": "말캉말캉 코트",
    "survival of the meanest": "혹독한 서바이벌",
    "the emptiness machine": "공허한 기계",
    "ticket to die": "저세상행 표",
    "unhappy arena": "불행의 아레나",
    "wispwillow ward": "위스프윌로우 구",
    "zone splitting": "존 스플릿",
  },
  "knockout": {
    "7개": "8개",
    "배구 브롤": "듀얼",
  },
  "knockout5v5": {
    "brawlerverse": "브롤러버스",
    "crescendo": "크레센도",
    "journey of a thousand steps": "수천 걸음의 여정",
    "serpentshrine island": "세르펜슈린 섬",
    "survival of the meanest": "혹독한 서바이벌",
    "the emptiness machine": "공허한 기계",
    "unhappy arena": "불행의 아레나",
  },
  "soloshowdown": {
    "acid lakes": "산성 호수",
    "catacombs": "카타콤",
    "cavern churn": "우당탕 진흙탕",
    "core of orbit": "궤도의 핵심",
    "crystal eye castle": "수정 눈의 성",
    "deathmatch": "데스매치",
    "double trouble": "더블 트러블",
    "feast or famine": "모 아님 도",
    "flying fantasies": "플라잉 판타지",
    "gated community": "출입 통제 커뮤니티",
    "kroket": "크로켓",
    "lilypond grove": "우거진 연못",
    "lotus": "로투스",
    "makeshift scaffolding": "임시 발",
    "mystical thirty three": "신비로운 33",
    "pound of mass": "질량의 무게",
    "reverse crossing": "리버스 교차로",
    "rockwall brawl": "바위 장벽 전투",
    "safety center": "안전 센터",
    "seeker": "시커",
    "skipyard": "스킵 한마당",
    "skull creek": "해골천",
    "time flies": "쏜살같은 시간",
    "truth": "진실",
    "twentyfive to two": "1시 35분",
    "twisting vines": "비틀린 덩쿨",
    "waveform": "파동",
    "wild greens": "와일드 그린",
    "wonderland": "원더랜드",
  },
  "spiritwars": {
    "cold snap": "차가운 스냅",
    "frostbite rink": "동상 링크장",
    "insane streamer": "크레이지 스트리머",
    "massive meltdown": "거대한 멜트다운",
    "pocket pleasures": "주머니 속 기쁨",
    "siberian stand off": "시베리아에서의 대결",
    "snowcone square": "스노우콘 광장",
    "stockpile stadium": "비축 스타디움",
  },
  "trophythieves": {
    "arctic ambush": "북극의 매복",
    "cobblestone swamp": "조약돌 늪",
    "public transport": "대중교통",
    "treasure island": "보물섬",
  },
  "wipeout": {
    "4개": "4개",
    "브롤 볼 5vs5": "잼그랩 5vs5",
  },
};